### ISSUE TITLE
Hi,can u share the link about oulp dataset? it's a little hard for me to get this dataset,because it need pwd to unzip...

### ISSUE THREAD

**Issue by xinyiamazing** [JinkaiZheng/TraND#1]

**Comment by JinkaiZheng** [comment]
Sorry, I can't give it to you directly. But I think you can try again according to the [AGREEMENT](http://www.am.sanken.osaka-u.ac.jp/BiometricDB/doc/OU-GaitLP_ReleaseAgreement.pdf)

**Comment by xinyiamazing** [comment]
okay..another question is in your modle ,after Stage II: Transferable Neighbor Discovery on Target Domain, i got the best_encoder .ptm and best_optimzer.ptm, what's the use of them in test _cross.py?

**Comment by JinkaiZheng** [comment]
You can refer to it [here](https://github.com/JinkaiZheng/TraND#test)
